//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_pacs
    {
        public int t_id { get; set; }
        public string t_pacspath { get; set; }
        public string t_resimad { get; set; }
        public string t_klasorad { get; set; }
        public string t_tc { get; set; }
        public int t_ip { get; set; }
        public string t_createuser { get; set; }
        public System.DateTime t_createdate { get; set; }
        public bool t_aktif { get; set; }
    }
}
