//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Users
    {
        public int t_id { get; set; }
        public string t_kodu { get; set; }
        public string t_adi { get; set; }
        public string t_sifre { get; set; }
        public string t_createuser { get; set; }
        public System.DateTime t_createdate { get; set; }
        public bool t_aktif { get; set; }
        public string GroupAd { get; set; }
        public Nullable<int> t_grup { get; set; }
    }
}
