//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_YetkiMethods
    {
        public long YetkiId { get; set; }
        public int YMId { get; set; }
        public string YetkiAdi { get; set; }
        public string YetkiAciklama { get; set; }
        public int MethodId { get; set; }
        public string MethodName { get; set; }
        public string GorunecekIsim { get; set; }
        public int ControllerId { get; set; }
        public string ControllerName { get; set; }
        public bool YetkiAktif { get; set; }
        public bool YMAktif { get; set; }
    }
}
