//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_MethodList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adm_MethodList()
        {
            this.adm_YetkiMethods = new HashSet<adm_YetkiMethods>();
        }
    
        public int MethodId { get; set; }
        public string MethodName { get; set; }
        public string GorunecekIsim { get; set; }
        public int ControllerId { get; set; }
    
        public virtual adm_ControllerList adm_ControllerList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adm_YetkiMethods> adm_YetkiMethods { get; set; }
    }
}
