//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_deneme
    {
        public Nullable<decimal> ODENDIMI { get; set; }
        public Nullable<decimal> KALAN { get; set; }
        public string ODEMETIPI { get; set; }
        public string t_tc { get; set; }
        public string t_adi { get; set; }
        public string t_soyadi { get; set; }
        public int t_id { get; set; }
        public System.DateTime t_basvurutarihi { get; set; }
        public int t_hizmetkodu { get; set; }
        public string Hizmet_Adı { get; set; }
        public decimal t_fiyat { get; set; }
        public int hisid { get; set; }
        public bool his_aktif { get; set; }
        public System.DateTime his_tarih { get; set; }
    }
}
