//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GroupYetki
    {
        public int UserId { get; set; }
        public Nullable<int> t_kid { get; set; }
        public string t_kodu { get; set; }
        public long YM_Id { get; set; }
        public long YetkiId { get; set; }
        public int MethodId { get; set; }
        public int GroupId { get; set; }
        public string groupAd { get; set; }
        public string YetkiAdi { get; set; }
        public string YetkiAciklama { get; set; }
        public string GorunecekIsim { get; set; }
        public string MethodName { get; set; }
        public string ControllerName { get; set; }
        public bool UserGroupAktif { get; set; }
        public bool YetkiAktif { get; set; }
        public bool UserAktif { get; set; }
    }
}
