//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL_CALLINGSCREEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_marka
    {
        public int t_id { get; set; }
        public int t_fid { get; set; }
        public string t_mad { get; set; }
        public bool t_aktif { get; set; }
    
        public virtual hst_firma hst_firma { get; set; }
    }
}
