//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL_CALLINGSCREEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_firma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hst_firma()
        {
            this.hst_his_hareket = new HashSet<hst_his_hareket>();
            this.hst_marka = new HashSet<hst_marka>();
        }
    
        public int t_id { get; set; }
        public string t_fad { get; set; }
        public bool t_aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hst_his_hareket> hst_his_hareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hst_marka> hst_marka { get; set; }
    }
}
