//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL_CALLINGSCREEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CeneDis
    {
        public int CeneNo { get; set; }
        public int DisNo { get; set; }
        public string CeneAd { get; set; }
        public bool Yetiskin { get; set; }
        public bool DisAktif { get; set; }
        public bool CeneAktif { get; set; }
    }
}
