//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adm_kullanicilar()
        {
            this.hst_basvuru = new HashSet<hst_basvuru>();
        }
    
        public int t_id { get; set; }
        public string t_kodu { get; set; }
        public string t_adi { get; set; }
        public string t_sifre { get; set; }
        public int t_grup { get; set; }
        public int t_yetki { get; set; }
        public string t_createuser { get; set; }
        public System.DateTime t_createdate { get; set; }
        public bool t_aktif { get; set; }
    
        public virtual adm_kullanicigrup adm_kullanicigrup { get; set; }
        public virtual adm_modulyetki adm_modulyetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hst_basvuru> hst_basvuru { get; set; }
    }
}
