//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_modulyetki
    {
        public adm_modulyetki()
        {
            this.adm_kullanicilar = new HashSet<adm_kullanicilar>();
        }
    
        public int t_id { get; set; }
        public string t_adi { get; set; }
        public string t_createuser { get; set; }
        public Nullable<System.DateTime> t_tarih { get; set; }
        public Nullable<bool> t_aktif { get; set; }
    
        public virtual ICollection<adm_kullanicilar> adm_kullanicilar { get; set; }
    }
}
