//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_pacs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adm_pacs()
        {
            this.hst_basvuru = new HashSet<hst_basvuru>();
        }
    
        public int t_id { get; set; }
        public string t_pacspath { get; set; }
        public decimal t_tc { get; set; }
        public int t_ip { get; set; }
        public string t_createuser { get; set; }
        public System.DateTime t_createdate { get; set; }
        public int t_aktif { get; set; }
    
        public virtual hst_hastakarti hst_hastakarti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hst_basvuru> hst_basvuru { get; set; }
    }
}
