//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_kullaniciyetki
    {
        public int t_id { get; set; }
        public int t_kod { get; set; }
        public int t_mid { get; set; }
        public bool t_yetki { get; set; }
    }
}
