//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adm_UserYetkis
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<long> YetkiId { get; set; }
        public int YMethodId { get; set; }
        public bool Aktif { get; set; }
    
        public virtual adm_kullanicilar adm_kullanicilar { get; set; }
    }
}
