//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class adm_kullanicigrup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adm_kullanicigrup()
        {
            this.adm_kullanicilar = new HashSet<adm_kullanicilar>();
        }
        [Display(Name = "Grup ID")]
        [Required]
        public int t_id { get; set; }
        [Display(Name = "Grup Adý")]
        [Required]
        public string t_adi { get; set; }
        [Display(Name = "Oluþturan Kullanýcý")]
        public string t_createuser { get; set; }
        [Display(Name = "Oluþturulan Tarih")]
        public System.DateTime t_createdate { get; set; }
        [Display(Name = "Aktif / Pasif")]
        public bool t_aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<adm_kullanicilar> adm_kullanicilar { get; set; }
    }
}
