//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class adm_modulyetki
    {

        [Display(Name = "Yetki ID")]
        [Required]
        public int t_id { get; set; }
        [Display(Name = "Yetki Adý")]
        [Required]
        public string t_adi { get; set; }
        [Display(Name = "Oluþturan Kullanýcý")]
        [Required]
        public string t_createuser { get; set; }
        [Display(Name = "Oluþturulma Tarihi")]
        [Required]
        public System.DateTime t_createdate { get; set; }
        [Display(Name = "Aktif / Pasif")]
        public bool t_aktif { get; set; }
    }
}
