//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class hst_basvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hst_basvuru()
        {
            this.hst_his_hareket = new HashSet<hst_his_hareket>();
            this.hst_vezne = new HashSet<hst_vezne>();
        }
    
        public int t_id { get; set; }
        public string t_basvuru { get; set; }
        [Required]
        public string t_tc { get; set; }
        public System.DateTime t_basvurutarihi { get; set; }
        public int t_bolumkodu { get; set; }
        public int t_cagriekraniistem { get; set; }
        public Nullable<int> t_basvurudr { get; set; }
        public bool t_taburcu { get; set; }
        public bool t_borc { get; set; }
        public System.DateTime t_createdate { get; set; }
        public string t_createuser { get; set; }
        public bool t_aktif { get; set; }
    
        public virtual hst_bölüm hst_bölüm { get; set; }
        public virtual hst_hastakarti hst_hastakarti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hst_his_hareket> hst_his_hareket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hst_vezne> hst_vezne { get; set; }
    }
}
