//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_hizmet_parca
    {
        public hst_hizmet_parca()
        {
            this.hst_hizmet = new HashSet<hst_hizmet>();
        }
    
        public int t_id { get; set; }
        public string t_adi { get; set; }
        public string t_createuser { get; set; }
        public Nullable<System.DateTime> t_tarih { get; set; }
        public Nullable<bool> t_aktif { get; set; }
    
        public virtual ICollection<hst_hizmet> hst_hizmet { get; set; }
    }
}
