//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_disno
    {
        public int t_id { get; set; }
        public int t_disno { get; set; }
        public int t_cene { get; set; }
        public bool t_yetiskinmi { get; set; }
        public bool t_aktif { get; set; }
    
        public virtual hst_cene_uygunmu hst_cene_uygunmu { get; set; }
    }
}
