//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_basvuru
    {
        public hst_basvuru()
        {
            this.hst_his_hareket = new HashSet<hst_his_hareket>();
        }
    
        public int t_id { get; set; }
        public string t_basvuru { get; set; }
        public Nullable<decimal> t_tc { get; set; }
        public Nullable<System.DateTime> t_basvurutarihi { get; set; }
        public Nullable<int> t_bolumkodu { get; set; }
        public Nullable<bool> t_cagriekraniistem { get; set; }
        public Nullable<int> t_pacsid { get; set; }
        public Nullable<bool> t_aktif { get; set; }
        public Nullable<int> t_basvurudr { get; set; }
    
        public virtual adm_kullanicilar adm_kullanicilar { get; set; }
        public virtual adm_pacs adm_pacs { get; set; }
        public virtual hst_bölüm hst_bölüm { get; set; }
        public virtual ICollection<hst_his_hareket> hst_his_hareket { get; set; }
    }
}
