//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_randevu
    {
        public int t_id { get; set; }
        public int t_basvuru { get; set; }
        public decimal t_tc { get; set; }
        public System.DateTime t_tarih { get; set; }
        public System.DateTime t_basgicsaat { get; set; }
        public System.DateTime t_bitissaat { get; set; }
        public string t_createuser { get; set; }
        public System.DateTime t_createdate { get; set; }
        public bool t_aktif { get; set; }
        public bool t_basvurudr { get; set; }
    }
}
