//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_weincoptions
    {
        public int t_id { get; set; }
        public string t_sure { get; set; }
        public string t_kayittarihi { get; set; }
        public string t_kullanici { get; set; }
        public string t_sifre { get; set; }
        public string t_serial { get; set; }
        public string t_yetki { get; set; }
        public Nullable<System.DateTime> t_createdate { get; set; }
        public string t_aktif { get; set; }
    }
}
