//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_hastakarti
    {
        public int t_id { get; set; }
        public int t_tc { get; set; }
        public string t_adi { get; set; }
        public string t_soyadi { get; set; }
        public int t_cinsiyet { get; set; }
        public int t_medenidurum { get; set; }
        public System.DateTime t_dogumtarihi { get; set; }
        public string t_dogumyeri { get; set; }
        public int t_tel1 { get; set; }
        public Nullable<int> t_tel2 { get; set; }
        public int t_ilId { get; set; }
        public int t_ilceId { get; set; }
        public string t_adres { get; set; }
        public string t_createuser { get; set; }
        public System.DateTime t_createdate { get; set; }
        public bool t_aktif { get; set; }
    
        public virtual hst_cinsiyet hst_cinsiyet { get; set; }
        public virtual hst_il hst_il { get; set; }
        public virtual hst_ilce hst_ilce { get; set; }
        public virtual hst_medenidurum hst_medenidurum { get; set; }
    }
}
