//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hst_his_hareket
    {
        public int t_id { get; set; }
        public int t_basvuruid { get; set; }
        public int t_hizmetkodu { get; set; }
        public System.DateTime t_islemtarihi { get; set; }
        public Nullable<int> t_ay { get; set; }
        public Nullable<int> t_yil { get; set; }
        public int t_diskodu { get; set; }
        public int t_parca { get; set; }
        public int t_cene { get; set; }
        public bool t_yetiskinmi { get; set; }
        public bool t_odemevarmi { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<decimal> t_totalborc { get; set; }
        public bool t_borcdurum { get; set; }
        public Nullable<int> t_firmaid { get; set; }
        public string t_createuser { get; set; }
        public System.DateTime t_createdate { get; set; }
        public bool t_aktif { get; set; }
        public Nullable<bool> t_yapildi { get; set; }
    
        public virtual hst_basvuru hst_basvuru { get; set; }
        public virtual hst_cene_uygunmu hst_cene_uygunmu { get; set; }
        public virtual hst_firma hst_firma { get; set; }
        public virtual hst_hizmet hst_hizmet { get; set; }
    }
}
