//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_ilçe
    {
        public t_ilçe()
        {
            this.hst_hastakarti = new HashSet<hst_hastakarti>();
            this.hst_il = new HashSet<hst_il>();
        }
    
        public int t_id { get; set; }
        public string t_adi { get; set; }
        public Nullable<bool> t_aktif { get; set; }
    
        public virtual ICollection<hst_hastakarti> hst_hastakarti { get; set; }
        public virtual ICollection<hst_il> hst_il { get; set; }
    }
}
