//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;

    public partial class View_Vezne
    {
        public int bid { get; set; }
        public int Vezneid { get; set; }
        public int hareket_id { get; set; }
        public string t_tc { get; set; }
        public string t_adi { get; set; }
        public string t_soyadi { get; set; }
        public System.DateTime t_basvurutarihi { get; set; }
        [DataType(DataType.Currency)]
        public decimal t_odenen { get; set; }
        [DataType(DataType.Currency)]
        public decimal BirimFiyat { get; set; }
        [DataType(DataType.Currency)]
        public decimal t_kalan { get; set; }
        [DataType(DataType.Currency)]
        public decimal t_total { get; set; }
        [DataType(DataType.Currency)]
        public decimal t_indirim { get; set; }
        [DataType(DataType.Currency)]
        public decimal OdenecekTutar { get; set; }
        public string OdemeTipi { get; set; }
        public int t_hizmetkodu { get; set; }
        public string Hizmet { get; set; }
        public System.DateTime t_islemtarihi { get; set; }
        public int t_diskodu { get; set; }
        public string CeneDurum { get; set; }
        public int t_parca { get; set; }
        public int t_cene { get; set; }
        public bool t_yetiskinmi { get; set; }
        public bool t_borcdurum { get; set; }
        public bool VezneAktif { get; set; }
        public bool BasvuruAktif { get; set; }
        public bool HHareketAktif { get; set; }
        public bool HastaAktif { get; set; }
    }
}
