//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Vezne
    {
        public string t_tc { get; set; }
        public string t_adi { get; set; }
        public string t_soyadi { get; set; }
        public string t_basvuru { get; set; }
        public System.DateTime t_basvurutarihi { get; set; }
        public string Doktoradi { get; set; }
        public int Hareketid { get; set; }
        public int t_hizmetkodu { get; set; }
        public string Hizmetadi { get; set; }
        public decimal t_fiyat { get; set; }
        public System.DateTime Hizmettarih { get; set; }
        public bool t_odemevarmi { get; set; }
        public decimal t_odenen { get; set; }
        public decimal t_kalan { get; set; }
        public string Odemetip { get; set; }
        public System.DateTime Odemetarih { get; set; }
    }
}
