//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Vezne
    {
        public string t_tc { get; set; }
        public string t_adi { get; set; }
        public string t_soyadi { get; set; }
        public System.DateTime DTarih { get; set; }
        public System.DateTime t_basvurutarihi { get; set; }
        public string Doktoradi { get; set; }
        public int Hareketid { get; set; }
        public int t_hizmetkodu { get; set; }
        public string Hizmetadi { get; set; }
        [DataType(DataType.Currency)]
        public decimal t_fiyat { get; set; }
        [DataType(DataType.Currency)]
        public Nullable<decimal> ToplamBorc { get; set; }
        public System.DateTime Hizmettarih { get; set; }
        public bool t_odemevarmi { get; set; }
        [DataType(DataType.Currency)]
        public decimal t_odenen { get; set; }
        [DataType(DataType.Currency)]
        public decimal t_kalan { get; set; }
        public string Odemetip { get; set; }
        public System.DateTime Odemetarih { get; set; }
        public bool t_borcdurum { get; set; }
        public int t_basvuruid { get; set; }
        public bool VezneAktif { get; set; }
        public bool HHareketAktif { get; set; }
    }
}
