//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEINCDENTAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_kullaniciYetki
    {
        public int yetkiId { get; set; }
        public int kullaniciId { get; set; }
        public int methodId { get; set; }
        public string groupAd { get; set; }
        public string methodAd { get; set; }
        public string methodAciklama { get; set; }
        public bool yetki { get; set; }
    }
}
